version: '3.8'

services:
  web:
<<<<<<< HEAD
    container_name: flask-app
=======
>>>>>>> 7d693a82924c567a74d8690d228ccbdc44a8f313
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
<<<<<<< HEAD
    volumes:
      - grafana-storage:/var/lib/grafana
=======
>>>>>>> 7d693a82924c567a74d8690d228ccbdc44a8f313
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
<<<<<<< HEAD

volumes:
  grafana-storage:
=======
>>>>>>> 7d693a82924c567a74d8690d228ccbdc44a8f313
